[package]
name = "aoc-2015"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
regex = "1"
fancy-regex = "0"

# day 4
md-5 = "0.9.1"
